name: Tests

on: [push, pull_request]

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: python:3.8

    services:
      mobilitydb:
        image: codewit/mobilitydb
        ports:
          - 5432:5432

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.4

      - name: Setup dependencies
        run: |
          apt-get -qq update
          apt-get -yqq install libgeos-dev libproj-dev proj-data proj-bin libgdal-dev
          poetry install
          poetry install -E movingpandas

      - name: Test with pytest
        run: poetry run pytest
        env:
          MOBILITYDB_HOST: mobilitydb
          MOBILITYDB_PORT: ${{ job.services.mobilitydb.ports[5432] }}
